### ISSUE TITLE
Prime and PrimeInverse calculations

### ISSUE THREAD

**Issue by a-shawky** [GeReV/Ishunator#1]
HI,

your way of obfuscating intergers was mentioned in link
http://stackoverflow.com/questions/8755713/user-id-obfuscation

the stackoverflow post refer to like below about calculating prime and primeinverse at link below
http://www.miguelsanmiguel.com/2011/04/03/hideous-obfuscated-ids
but the link is not working.

Please tell me how to calculate Prime and Prime inverse.

**Comment by GeReV** [comment]
Hi,

To be honest, I can't remember how to do that myself, but I found something that seems to cover the process:
https://www.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/modular-inverses

I hope this helps.
